conformant = "Unsupported"
notes = """
Does not support covariant or contravariant TypeVars.
"""
output = """
File "generics_variance.py", line 14, in <module>: argument "covariant" to TypeVar not supported yet [not-supported-yet]
File "generics_variance.py", line 14, in <module>: argument "contravariant" to TypeVar not supported yet [not-supported-yet]
File "generics_variance.py", line 18, in <module>: argument "covariant" to TypeVar not supported yet [not-supported-yet]
File "generics_variance.py", line 19, in <module>: argument "contravariant" to TypeVar not supported yet [not-supported-yet]
File "generics_variance.py", line 27, in __iter__: bad return type [bad-return-type]
File "generics_variance.py", line 52, in <module>: argument "covariant" to TypeVar not supported yet [not-supported-yet]
"""
conformance_automated = "Fail"
errors_diff = """
Line 77: Expected 1 errors
Line 81: Expected 1 errors
Line 93: Expected 1 errors
Line 105: Expected 1 errors
Line 113: Expected 1 errors
Line 142: Expected 1 errors
Line 163: Expected 1 errors
Line 167: Expected 1 errors
Line 191: Expected 1 errors
Line 196: Expected 1 errors
Lines 125, 126: Expected error (tag 'CoContra_Child2')
Lines 131, 132: Expected error (tag 'CoContra_Child3')
Line 18: Unexpected errors ['File "generics_variance.py", line 18, in <module>: argument "covariant" to TypeVar not supported yet [not-supported-yet]']
Line 19: Unexpected errors ['File "generics_variance.py", line 19, in <module>: argument "contravariant" to TypeVar not supported yet [not-supported-yet]']
Line 27: Unexpected errors ['File "generics_variance.py", line 27, in __iter__: bad return type [bad-return-type]']
Line 52: Unexpected errors ['File "generics_variance.py", line 52, in <module>: argument "covariant" to TypeVar not supported yet [not-supported-yet]']
"""
